### ISSUE TITLE
handle "der*die" / "einer*eine"

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#132]
![image](https://user-images.githubusercontent.com/300279/137724168-cd2b8190-773b-4ccf-8991-2031c1e70be2.png)

**Comment by lnazarenko** [comment]
done

**Comment by lsmith77** [comment]
I was playing with that a bit and I think we need to make it a bit smarter. if I have the sentence `Was ist zu tun, wenn der Kunde mehr will?` .. then we will suggest to change der to der:die and Kunde to Kund:in.

I think we should first suggest to only Kunde and as soon as its changed to one of the inclusive formats, ie Kund:in, Kund*in, Kundin/Kunde we would then suggest a matching variation .. ie. der:die, der*die, der/die .. do you think this is possible? note right now as soon as we change Kunde to Kund:in we stop suggesting to change der
