### ISSUE TITLE
languagetool app

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#146]
figure out how to set LANGUAGETOOL_API appropriately during deployment of the python app

**Comment by lsmith77** [comment]
* https://github.com/Erikvl87/docker-languagetool
* https://github.com/silvio/docker-languagetool

**Comment by lsmith77** [comment]
https://github.com/witty-works/nlp_api/tree/dev/languagetool

**Comment by lsmith77** [comment]
https://www.notion.so/witty-works/LanguageTool-241f0637f4654d5082df217c2891a47d

**Comment by lsmith77** [comment]
https://forum.languagetool.org/

**Comment by Szarad** [comment]
I used Docker image from first repo you sent me: https://github.com/Erikvl87/docker-languagetool.
I build it locally to not be dependent on changes and it works good. The image is put on the nlp-api Github repository and the Azure Container Registry (wittyworks).
