### ISSUE TITLE
check the lemmatization for Swiss German vs German words with ß

### ISSUE THREAD

**Issue by lnazarenko** [witty-works/nlp_api#149]

**Comment by lsmith77** [comment]
generally in the rules I defined we use `ß` since its easier to then extrapolate to `ss`, because not all `ss` convert to `ß` in high german.

see also https://www.notion.so/witty-works/Rule-Guidelines-432792da944141b1b4d0a01de290aa43

**Comment by lnazarenko** [comment]
Ok, thank you! So there is no need to create two version of the same word in the excel sheet, right? This question related to Tracey since she started to create two version (German and Swiss German) in the sheet.

**Comment by lsmith77** [comment]
yeah .. the vision would be to minimize the duplication inside the sheet and automate it instead.

**Comment by lnazarenko** [comment]
Was already handle
