### ISSUE TITLE
Sync to NLP API

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#154]
* [x] HTTP API to receive and store (Redis?) corporate rules
* [x] Read corporate rules from the store (Redis?)
  * use `id` field to determine organization, ie: `lukas.smith@witty.works` => `witty.works` organization
  * check Redis DB if `witty.works` has corporate rules
  * if the organizaton has corporate rules, apply them to the `config`
  * ideally with each setting the corporate rules can define if its "just a default" or if the setting cannot be different and therefore the corporate rules override the relevant user setting (f.e. `store_context` might be forced to `false` while `preferred_variants` is just a corporate default
* [x] Apply appropriate defaults or overrides

defaults for the config need to be configurable:
https://github.com/witty-works/nlp_api/blob/dev/app/models.py#L49

https://www.notion.so/witty-works/Configuration-Options-41edc3d969ec49f189d361fb112b1e80

https://docs.platform.sh/configuration/services/redis.html

same for custom false positive lists:
https://github.com/witty-works/nlp_api/compare/65ff1f6f4cb1...1ced1703cc00#diff-990f7e4140fab1ad82afc787505090b64d4024e63a891405cd9085e7e6b249ddR241

**Comment by lsmith77** [comment]
Link to subfeature: https://wittyworks.productboard.com/feature-board/planning/features/10416768

**Comment by Szarad** [comment]
just to clarify, we want to use Redis as database, not cache?

**Comment by lsmith77** [comment]
Basically the data will be stored in the Dashboard MySQL database but replicated over to the NLP API. Redis would therefore not be the source database as we could rebuild its content in short time from the MySQL database if necessary. as such I would use only an in-memory database for optimal performance.
