### ISSUE TITLE
add demo wordings to tests

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#183]
we should have tests that cover all the sentences in https://www.notion.so/witty-works/Demo-wordings-76a899ac154c41d29061f2c4ea5f5fd9

**Comment by Szarad** [comment]
Tests are added on branch `183-add-demo-wordings` . Outputs are not correct, but as expected from notion documentation. Should this wait till the algorithm will be 100% correct? When waiting, we can check whenever updated on NLP side is done.

**Comment by lsmith77** [comment]
ideally we could somehow visualize the delta from our ideal and currently reality. but I think for now having the test helps to expand our test suite but more importantly so that we know when we have gotten closer to our target.

**Comment by lsmith77** [comment]
BTW can you open a PR?

**Comment by Szarad** [comment]
PR is created

**Comment by lsmith77** [comment]
closed via https://github.com/witty-works/nlp_api/pull/281
