### ISSUE TITLE
add Azure Python Monitor

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#184]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python

```
if os.getenv("INSTRUMENTATION_KEY"):
    from opencensus.ext.azure.log_exporter import AzureLogHandler
    logger.addHandler(AzureLogHandler(
    connection_string='InstrumentationKey={}'.format(os.getenv("INSTRUMENTATION_KEY"))
)
```

https://wittyworks.slack.com/archives/C02L5KQ3LTV/p1637048099001300

**Comment by Szarad** [comment]
I see that the only logging we are doing is writing body of the request to a file.  To use Azure monitor of python app I would need to replace that with logging + fileHandler + azureHandler. Is it ok with you?

**Comment by Szarad** [comment]
or for the moment let's keep the exiting code and refactor it in the future

**Comment by lsmith77** [comment]
can't we do the azureHandler if `INSTRUMENTATION_KEY` is available and otherwise do our own logging?
