### ISSUE TITLE
Highlight whole term instead of just german gender ending

### ISSUE THREAD

**Issue by arnaumanyosa** [witty-works/nlp_api#196]
Currently API highlights german gender endings but not the whole term that includes it. Maybe it would be nicer and more understandable to include the whole term?

See screenshot
<img width="683" alt="Screen Shot 2021-11-19 at 21 20 18" src="https://user-images.githubusercontent.com/5278398/142687443-51519366-4d45-4df0-ad86-6e0865f3f751.png">

So instead of highlighting `:in` in `Kolleg:innen`, highlight the whole  `Kolleg:innen`
The same with the alternative given: instead of giving just `/in`, give  `Kolleg/innen`

**Comment by lsmith77** [comment]
lets keep as it for now
