### ISSUE TITLE
Category: German Inclusive

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#223]

**Comment by lsmith77** [comment]
Link to feature: https://wittyworks.productboard.com/feature-board/planning/features/10835203

**Comment by lnazarenko** [comment]
data files updated. Might be closed

**Comment by lsmith77** [comment]
`LGBTQIA+` does not seem to be handled properly. I think its both related to all capital letters as well as the `+` sign.

Also words with umlauts do not seem to be detected like `präzise`

**Comment by lsmith77** [comment]
`keine Diskriminierung` also does not seem to be handled properly
