### ISSUE TITLE
If Service does not detect the language, should not return a 400

### ISSUE THREAD

**Issue by arnaumanyosa** [witty-works/nlp_api#225]
If I understand correctly, service returns an error 400 when language is not detected. This error means:

`The HyperText Transfer Protocol (HTTP) 400 Bad Request response status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (for example, malformed request syntax, invalid request message framing, or deceptive request routing).`

Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

which is not the case.

In this case I would return a valid 200 response with something like this

```
{
  "results": [],
  "language": "Language could not be determined"
}
```

**Comment by lsmith77** [comment]
it is a bit tricky .. there isn't an error code for this .. if its the fault of the client or the server is also debatable. 

one could argue 422 is maybe more appropriate?

imho returning a 200 is misleading since the purpose of the request could not be full-filled.

at the end of the day this is all somewhat academic. what is the issue created due to the 400 response?

**Comment by arnaumanyosa** [comment]
The issue is very minor, more of a formality: in my understanding this should not be treated as an error and should not be shown on the console as it.

This issue is very low priority, but I wanted to document it. And below follows my explanation but I insist, is not something urgent to spend time with :)

> at the end of the day this is all somewhat academic.

Agree with this

> there isn't an error code for this .. if its the fault of the client or the server is also debatable.

There isn't an error code because IMO this is not an error. It's not a fault from the client or the server. It's just that language could not be detected.

I'm far from being an expert but I understand that this codes just reflect the success or not of the communication, nothing else.

From the documentation https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

`HTTP response status codes indicate whether a specific HTTP request has been successfully completed.`

The description for a `200` for `POST` is

`PUT or POST: The resource describing the result of the action is transmitted in the message body.`

Which for me is exactly the case. The result of the action is that I could not determine the language.

**Comment by lsmith77** [comment]
https://twitter.com/lsmith/status/1472968908277788677

**Comment by lsmith77** [comment]
How about

```
422 Unprocessable Entity
The HyperText Transfer Protocol (HTTP) 422 Unprocessable Entity response status code indicates that the server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions.
```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422

**Comment by lsmith77** [comment]
FYI Languagetool uses 400, which is probably why I am also using 400

**Comment by lsmith77** [comment]
lets tackle this when we move to background scripts in the browser extension
