### ISSUE TITLE
"Ghost" violet button

### ISSUE THREAD

**Issue by lnazarenko** [witty-works/nlp_api#246]
When you type Macht

**Comment by lsmith77** [comment]
@lnazarenko can you elaborate here? or shall we just close this issue?

**Comment by arnaumanyosa** [comment]
Don't close it, I have it under control. It's a "bug" with the alternative buttons.

**Comment by arnaumanyosa** [comment]
@lnazarenko @lsmith77 

This example (`Macht`) returns an alternative `''`

<img width="642" alt="Screenshot 2021-12-07 at 15 16 02" src="https://user-images.githubusercontent.com/5278398/145045448-f6d98754-897c-4116-af70-50a38b000877.png">

If I remember correctly this is not an expected alternative output. I can control it on the client side but maybe you want to fix it in the backend?

**Comment by lsmith77** [comment]
yeah indeed .. we should return either `[]` or `["-"]` here.

@lnazarenko I will do a quick fix here and you will ensure to fix it in the pre-processing script?

**Comment by arnaumanyosa** [comment]
Then, can we close this issue? @lsmith77

**Comment by lsmith77** [comment]
fixed via https://github.com/witty-works/nlp_api/commit/124716f4408c479d6ac1e2b9ee2130e7bb8b390b
