### ISSUE TITLE
Partner:innen is not handled correctly

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#265]
Is: I am in Gmail an write "Partner:innen-Vertrag" (without having used the replace function - I just did it myself correctly from the start) -> Partner gets underlined and the alternative given is "Partner:in"

<img width="382" alt="Bildschirmfoto 2021-12-16 um 22 00 43" src="https://user-images.githubusercontent.com/300279/146514083-ff6fb5b9-4e99-4831-84db-2122366ba10a.png">

Should: I write it correctly form the start, so it should not underline anything.

**Comment by lsmith77** [comment]
Link to feature: https://wittyworks.productboard.com/feature-board/planning/features/11195346

**Comment by lnazarenko** [comment]
The list of false positives is not updated yet with new glossary

**Comment by lsmith77** [comment]
there might be some overlap here with what @Szarad is doing generating a false positive list for LT https://github.com/witty-works/nlp_api/pull/249
