### ISSUE TITLE
Underline disappears with trailing space 

### ISSUE THREAD

**Issue by hellasol** [witty-works/nlp_api#283]
<img width="119" alt="Dominant" src="https://user-images.githubusercontent.com/45122311/148190729-29dd14ef-36ec-4b06-a402-6c6c1d542774.png">
<img width="168" alt="Dominant person" src="https://user-images.githubusercontent.com/45122311/148190750-794b6d06-5094-4fbe-bd4b-7475bdc952d4.png">
<img width="180" alt="Dominant" src="https://user-images.githubusercontent.com/45122311/148190757-8ab05cb9-29b7-4064-a27a-7b85c11ac63d.png">

**Comment by lsmith77** [comment]
I suspect this is rather a browser ext bug. will verify this afternoon.

**Comment by hellasol** [comment]
@lsmith77 I discussed it with Arnau yesterday, and he also thought it was an issue on the backend.

**Comment by Szarad** [comment]
For me it seems like bug in Spacy model for `token:"Dominant " token.lemma_:"Dominant"` (with Capital letter), which messes up if clause `if token.lemma_ == word` in main.py [line 1237]. I tried a few words from the same group and they work fine. The workaround could be to strip user text, before creating tokens, but it needs to be checked with @lnazarenko if it really makes sense.

**Comment by Szarad** [comment]
We checked it with @lnazarenko on Wednesday. It is indeed problem with Spacy model. Elena wrote to one of the developer regarding this issue. Till then we can apply the small workaround using strip() function when generating token, which should not modify correct behavior (I am creating PR now). @lnazarenko will also check with there are any other problematic words in English (I checked just couple).
