### ISSUE TITLE
automate rule updates

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#288]
* [x] https://github.com/witty-works/nlp_api/issues/343
* [x] #289
* [x] #290
  * [ ] make sure to [generate GB rules](https://github.com/witty-works/nlp_api/blob/dev/sync-GB-training-data.sh) 
  * [ ] probably initially for now sending the changes as an email?
  * [ ] eventually automatically create a PR with the training-data updates
* [ ] integrating the QA scripts
  * [x] fine overlaps in lemma and alternatives and typos with our syntax rules
    * https://github.com/witty-works/nlp_api/blob/dev/analyze_rules.py
    * see also https://www.notion.so/witty-works/QA-Clean-rules-lemma-in-alternatives-04e2d983785044198a76d64b5edf94cd
  * [ ] find potential spelling mistakes and update false positive lists
    * https://github.com/witty-works/nlp_api/blob/dev/add_alternatives_to_ignore.py

**Comment by lsmith77** [comment]
Link to feature: https://wittyworks.productboard.com/feature-board/planning/features/11429512

**Comment by Szarad** [comment]
closing, it will be done in Rule Editor [issue 5](https://github.com/witty-works/rule-editor/issues/5)
