### ISSUE TITLE
shaping the current Jupyter notebooks to generate the training-data files into re-useable code

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#289]
see also https://github.com/witty-works/nlp_jupyter_notebook (likely out of date)
Scripts integrated with Azure Function:
- [x] [Hyphen_transform_English.ipynb](https://github.com/witty-works/nlp_jupyter_notebook/blob/dev/Hyphen_transform_English.ipynb)
- [x] [analyze_rules.py](https://github.com/witty-works/nlp_api/blob/dev/analyze_rules.py)
- [ ] German lemmatizer
- [ ] scripts to generate multiple csv files depending on category

**Comment by Szarad** [comment]
Scripts integrated with Azure Function:
- [x] [Hyphen_transform_English.ipynb](https://github.com/witty-works/nlp_jupyter_notebook/blob/dev/Hyphen_transform_English.ipynb)
- [x] [analyze_rules.py](https://github.com/witty-works/nlp_api/blob/dev/analyze_rules.py)

Scripts to integrate with Azure Function:

**Comment by Szarad** [comment]
closing, it will be done in Rule Editor [issue 5](https://github.com/witty-works/rule-editor/issues/5)
