### ISSUE TITLE
properly handle newlines

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#331]
API calls with "\n" can lead to not detecting issues, in this example `intern` is not detected

this relates to #295 (initial fix was the replace `\n` with ` `) and #327 (reverted that fix since it was causing issues with start/end)

```
Hi Siwar,\n\nit's the first time that we are looking for a intern\nThomas Jung\nHead of Talent Acquisition EMEA\n\nFossil Group Europe GmbH\nRiehenring 182\n\n4058 Basel\nSWITZERLAND\nwww.fossilgroup.com\nt: +41 61 560 99 69\nm: +41 78 625 82 95\ne: tjung@fossil.com\n\n\n
```

see also https://github.com/explosion/spaCy/issues/4792

**Comment by lsmith77** [comment]
```
Foo
Bar
```

=> "Foo\nBar"
=> "Foo  Bar" (ie. 2 spaces for one `\n`)

**Comment by lnazarenko** [comment]
well, don't really understand the issue with "Engineering". This is not a trigger word, this word is in alternatives

**Comment by lsmith77** [comment]
strange indeed. we do have “Engineer” but I don’t think it would trigger on “Engineering”

the issue I connected is about cases where we are unable to figure out if its singular or plural, which we originally found to be triggered (with some frequency) with this new line issue. but I suspect that there are more cases than just what is fixed here.
