### ISSUE TITLE
Typing 'liebe kunde' returns 'language could not be determined'

### ISSUE THREAD

**Issue by arnaumanyosa** [witty-works/nlp_api#334]
<img width="1073" alt="Screen Shot 2022-01-24 at 14 45 24" src="https://user-images.githubusercontent.com/5278398/150794148-ec100816-4c13-4fb7-8438-15541e9e1835.png">

**Comment by lsmith77** [comment]
yeah this is expected .. the text is too short and there are too many grammatical mistakes.

it works with `lieber kunde` or `liebe Kunde` (both of which are also not correct but less incorrect)
