### ISSUE TITLE
add missing words to eng

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#356]
there seem to be some words missing on https://github.com/orsinium-labs/eng/blob/master/eng/words.txt

like skillful and willfully

**Comment by lsmith77** [comment]
see also https://www.notion.so/witty-works/Review-ignore-txt-files-9db375b0462d475eb02e647c761c2459

**Comment by Szarad** [comment]
https://github.com/orsinium-labs/eng/pull/2 pull request with missing words and `lower()` function
