### ISSUE TITLE
accidental code duplication in set_rules() 

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#362]
see https://github.com/witty-works/nlp_api/blob/dev/app/main.py#L372:L384

The following code is both in an `elif` and `else` statement immediately following, so I guess we can remove the `elif` statement

```
setattr(
  user_request_in.config, config_value, user_rules[config_value]
)
```

**Comment by Szarad** [comment]
thank you for noticing it! I created a PR.
