### ISSUE TITLE
Migrate rules to ß

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#48]
For German we need `ß`. So we should convert all of our rules to use `ß` and then for Swiss German customers we need actually start supporting de_CH where we convert all `ß` to `ss`

**Comment by nadiazuerich** [comment]
I need to check with Elena on what she relies.

**Comment by lsmith77** [comment]
I have updated https://docs.google.com/spreadsheets/d/1A6aMrGpVNb8igIrGJxDek9Vvie-zXzPaMq5M84ptP0M/edit#gid=1744386572 accordingly

@lnazarenko we can close this ticket as soon as you have synced the training data
