### ISSUE TITLE
Endpoint /check breaks when using long text

### ISSUE THREAD

**Issue by arnaumanyosa** [witty-works/nlp_api#50]
Using the text 

```Er ersetzt Deutsch um Designelemente gegenüber dem Inhalt hervorzuheben, hat also die Funktion als Platzhalters in Layouts um dem Betrachter eine vorläufige Vorstellung der endgültigen Fassung zu vermitteln. Buchstaben, Worte, Wort- und Satzlängen bilden ungefähr das Schriftbild eines lateinischen Texts wieder. Latein war in früheren Jahrhunderten eine häufig genutzte Sprache verschiedener Textgattungen, z. B. wissenschaftlicher Werke, Ratgeber, oder auch der sogenannten Erbauungsliteratur. Um die Aufmerksamkeit des Lesers ausschließlich auf das Schriftbild zu lenken wird auch ein zufälliger Sinn durch Wort- oder Satzkombinationen vermieden```

API returns Error 502

**Comment by arnaumanyosa** [comment]
I started trying the text that Christian Holz was testing the BE with and I find the same errors. See screenshots below.

Could be that 

* NLP API returns something not well formated or something like that 
* Browser extension does too many requests
* ...

> 502 Bad Gateway
> The HyperText Transfer Protocol (HTTP) 502 Bad Gateway server error response code indicates that the server, while > acting as a gateway or proxy, received an invalid response from the upstream server.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502

Could be related with https://github.com/witty-works/Inclusifier/issues/38

<img width="1162" alt="Screen Shot 2021-09-01 at 18 07 41" src="https://user-images.githubusercontent.com/5278398/131705664-1e91096b-16e0-4596-9271-a50d989eac83.png">

**Comment by lsmith77** [comment]
@lnazarenko I fear we are hitting some time-out and or memory issue here :-/

**Comment by lnazarenko** [comment]
@lsmith77 I can split the text into sentences. And it will analyse the text sentence by sentence, not all the text in one time

**Comment by lsmith77** [comment]
yeah .. lets try that

**Comment by lsmith77** [comment]
we moved back to just using Spacy which seems to have fixed this issue
