### ISSUE TITLE
German binary pronouns

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#548]
add to rule-editor and API

**Comment by lsmith77** [comment]
Link to feature: https://wittyworks.productboard.com/feature-board/planning/features/14629009

**Comment by lnazarenko** [comment]
Is German exist in rules editor? Karolina finished only English. I don't have time to support rules editor since I focus on Machine Learning now.

**Comment by lsmith77** [comment]
ah right .. German is still missing, see https://github.com/witty-works/rule-editor/issues/29

let us discuss this topic next week.

**Comment by lsmith77** [comment]
fixed via https://github.com/witty-works/nlp_api/pull/582
