### ISSUE TITLE
Implement DB specific rules

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#57]
follow up to https://github.com/witty-works/nlp_api/issues/23

goal is to implement as many gender language rules as possible and a few english formatting rules

https://docs.google.com/spreadsheets/d/1ZmJ0ARENYoNX7BPhCa3ZWl8x8VeXywNEZIEhZpv0tEI/edit#gid=1061596023

**Comment by lnazarenko** [comment]
done
