### ISSUE TITLE
context checker for german

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#762]

**Comment by lsmith77** [comment]
Link to feature: https://wittyworks.productboard.com/feature-board/planning/features/17933027

**Comment by lsmith77** [comment]
https://wittyworks.slack.com/archives/C03NET4EBE0/p1686039719027099

**Comment by lsmith77** [comment]
@lnazarenko can you give me the list of words in the german model?

**Comment by lnazarenko** [comment]
@lsmith77 for German: unabhängig, entschieden

**Comment by lnazarenko** [comment]
@lsmith77 REST endpoint: https://workspace-witty-western-eu-xwoas.westeurope.inference.ml.azure.com/score
Primary key: YC6EYEH9hED06k0SHhDhEVVggrb1TcBU
