### ISSUE TITLE
"Deutsche Bahn ist eine Partnerin"

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#93]
"Deutsche Bahn als Arbeitgeberin"

**Comment by lsmith77** [comment]
https://raw.githubusercontent.com/languagetool-org/languagetool/1e740fc3eed858e43ef218bb209b3f055ec0d9d0/languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml

search for `Evtl. keine Übereinstimmung von Kasus, Genus oder Numerus`

**Comment by lsmith77** [comment]
https://forum.languagetool.org/t/creating-custom-rules/7263

**Comment by lnazarenko** [comment]
done
